import { Geist, Geist_Mono } from "next/font/google";
import { Unbounded } from "next/font/google";
import { Poppins } from "next/font/google";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const unbounded = Unbounded({
  subsets: ["latin"],
  weight: ['500', '600'],
  variable: '--font-unbounded',
})

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ["latin"],
  variable: '--font-poppins',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body
        className={`${unbounded.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

