import type { Metadata } from "next";
import { Barlow_Semi_Condensed, Michroma } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "./AuthProvider";

const barlow = Barlow_Semi_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} text-base lg:text-xl antialiased`}
      >
        <AuthProvider>
          <Toaster position="top-center"/>
          {children}
          {modal}
        </AuthProvider>
      </body>
    </html>
  );
}
