import type { Metadata } from "next";
import { Barlow_Semi_Condensed, Michroma } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AuthProvider from "../components/providers/AuthProvider";
import ProgressProvider from "../components/providers/ProgressProvider";
import QueryProvider from "@/components/providers/QueryProvider";
import ThemesProvider from "@/components/providers/ThemesProvider";
import StyledComponentsRegistry from "@/lib/styled-components-registry";

const barlow = Barlow_Semi_Condensed({
  variable: "--font-barlow",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const michroma = Michroma({
  variable: "--font-michroma",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} text-base lg:text-xl antialiased`}
      >
        <StyledComponentsRegistry>
          <ThemesProvider>
            <ProgressProvider>
              <QueryProvider>
                <AuthProvider>
                  <Toaster position="top-center"/>
                  {children}
                  {modal}
                </AuthProvider>
              </QueryProvider>
            </ProgressProvider>
          </ThemesProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
